-- Tests build targets for Prism
-- All test targets are defined here and included from root xmake.lua

local common_files = {"$(projectdir)/src/*.cpp", "$(projectdir)/util/*.cpp", "$(projectdir)/include/table/*.cpp"}
local common_includedirs = {"$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/src", "$(projectdir)/util"}

add_packages("crc32c", "gtest")

target("coding_test")
    set_kind("binary")
    add_files(common_files)
    add_files("$(projectdir)/tests/coding_test.cpp")
    add_includedirs(common_includedirs)
    add_tests("default")

target("db_test")
    set_kind("binary")
    add_files(common_files)
    add_files("$(projectdir)/tests/db_test.cpp")
    add_includedirs(common_includedirs)
    add_tests("default")

target("skiplist_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/skiplist_test.cpp", "$(projectdir)/util/arena.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util")
    add_tests("default")

target("arena_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/arena_test.cpp", "$(projectdir)/util/arena.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util")
    add_tests("default")

target("dbformat_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/dbformat_test.cpp")
    add_files("$(projectdir)/src/*.cpp")
    add_files("$(projectdir)/util/*.cpp")
    add_files("$(projectdir)/include/table/*.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util")
    add_tests("default")

target("status_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/status_test.cpp")
    add_files("$(projectdir)/util/status.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util")
    add_tests("default")

target("result_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/result_test.cpp")
    add_files("$(projectdir)/util/status.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util")
    add_tests("default")

target("memtable_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/memtable_test.cpp")
    add_files("$(projectdir)/src/*.cpp")
    add_files("$(projectdir)/util/*.cpp")
    add_files("$(projectdir)/include/table/*.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util")
    add_tests("default")

target("block_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/block_test.cpp")
    add_files("$(projectdir)/src/*.cpp")
    add_files("$(projectdir)/util/*.cpp")
    add_files("$(projectdir)/include/table/*.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/src", "$(projectdir)/util")
    add_tests("default")

target("table_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/table_test.cpp")
    add_files("$(projectdir)/src/*.cpp")
    add_files("$(projectdir)/util/*.cpp")
    add_files("$(projectdir)/include/table/*.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/src", "$(projectdir)/util")
    add_tests("default")

target("filter_block_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/filter_block_test.cpp")
    add_files("$(projectdir)/src/*.cpp")
    add_files("$(projectdir)/util/*.cpp")
    add_files("$(projectdir)/include/table/*.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/src", "$(projectdir)/util")
    add_tests("default")

target("env_posix_test")
    set_kind("binary")
    add_files(common_files)
    add_files("$(projectdir)/tests/env_posix_test.cpp")
    add_includedirs(common_includedirs)
    add_tests("default")

target("asyncdb_test")
    set_kind("binary")
    add_files(common_files)
    add_files("$(projectdir)/tests/asyncdb_test.cpp")
    add_includedirs(common_includedirs)
    add_tests("default")

target("scheduler_stress_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/scheduler_stress_test.cpp")
    add_files("$(projectdir)/util/scheduler.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util")
    add_tests("default")

target("scheduler_context_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/scheduler_context_test.cpp")
    add_files("$(projectdir)/util/scheduler.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util")
    add_tests("default")

target("scheduler_shutdown_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/scheduler_shutdown_test.cpp")
    add_files("$(projectdir)/util/scheduler.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util")
    add_tests("default")

target("async_env_test")
    set_kind("binary")
    add_files(common_files)
    add_files("$(projectdir)/tests/async_env_test.cpp")
    add_includedirs(common_includedirs)
    add_tests("default")

target("async_op_test")
    set_kind("binary")
    add_files("$(projectdir)/tests/async_op_test.cpp")
    add_files("$(projectdir)/util/scheduler.cpp")
    add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util", "$(projectdir)/tests")
    add_tests("default")

target("scheduler_pending_regression_test")
	set_kind("binary")
	add_files("$(projectdir)/tests/scheduler_pending_regression_test.cpp")
	add_files("$(projectdir)/util/scheduler.cpp")
	add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util")
	add_tests("default")

target("scheduler_exceptions_test")
	set_kind("binary")
	add_files("$(projectdir)/tests/scheduler_exceptions_test.cpp")
	add_files("$(projectdir)/util/scheduler.cpp")
	add_includedirs("$(builddir)/generated", "$(projectdir)/include", "$(projectdir)/util")
	add_tests("default")

target("manifest_recovery_test")
	set_kind("binary")
	add_files(common_files)
	add_files("$(projectdir)/tests/manifest_recovery_test.cpp")
	add_includedirs(common_includedirs)
	add_tests("default")

target("fault_injection_test")
	set_kind("binary")
	add_files(common_files)
	add_files("$(projectdir)/tests/fault_injection_test.cpp")
	add_includedirs(common_includedirs)
	add_tests("default")

target("version_edit_test")
	set_kind("binary")
	add_files(common_files)
	add_files("$(projectdir)/tests/version_edit_test.cpp")
	add_includedirs(common_includedirs)
	add_tests("default")

target("version_set_test")
	set_kind("binary")
	add_files(common_files)
	add_files("$(projectdir)/tests/version_set_test.cpp")
	add_includedirs(common_includedirs)
	add_tests("default")

target("compaction_test")
	set_kind("binary")
	add_files(common_files)
	add_files("$(projectdir)/tests/compaction_test.cpp")
	add_files("$(projectdir)/tests/test_main.cpp")
	add_includedirs(common_includedirs)
	add_tests("default")

target("obsolete_files_test")
	set_kind("binary")
	add_files(common_files)
	add_files("$(projectdir)/tests/obsolete_files_test.cpp")
	add_files("$(projectdir)/tests/test_main.cpp")
	add_includedirs(common_includedirs)
	add_tests("default")

target("flush_compaction_test")
	set_kind("binary")
	add_files(common_files)
	add_files("$(projectdir)/tests/flush_compaction_test.cpp")
	add_files("$(projectdir)/tests/test_main.cpp")
	add_includedirs(common_includedirs)
	add_tests("default")

target("compaction_picker_test")
	set_kind("binary")
	add_files(common_files)
	add_files("$(projectdir)/tests/compaction_picker_test.cpp")
	add_includedirs(common_includedirs)
	add_tests("default")

target("compaction_execution_test")
	set_kind("binary")
	add_files(common_files)
	add_files("$(projectdir)/tests/compaction_execution_test.cpp")
	add_files("$(projectdir)/tests/test_main.cpp")
	add_includedirs(common_includedirs)
	add_tests("default")

target("kv_bench_async_matrix_test")
	set_kind("binary")
	add_files(common_files)
	add_files("$(projectdir)/benchmark/kv_bench_lib.cpp")
	add_files("$(projectdir)/tests/kv_bench_async_matrix_test.cpp")
	add_files("$(projectdir)/tests/test_main.cpp")
	add_includedirs(common_includedirs)
	add_includedirs("$(projectdir)/benchmark")
	add_tests("default")
